### ISSUE TITLE
error when running sh install.sh on mac os

### ISSUE THREAD

**Issue by darwinbandoy** [HDI-Project/ATMSeer#31]
I tried running the sh install.sh command but I got this error message: 

Submodule path 'lib/atm': checked out '9dfe5d9c883efc37d285c852fcc92a02c6cdd945'
install.sh: line 7: vagrant: command not found
install.sh: line 8: vagrant: command not found

**Comment by micahjsmith** [comment]
Hello, did you install Vagrant and VirtualBox as required in the installation instructions?

**Comment by micahjsmith** [comment]
Feel free to reopen if you are able to provide a reproducible example for the dev team, thanks.
