### ISSUE TITLE
sudo sh install-docker.sh

### ISSUE THREAD

**Issue by 3303387067** [HDI-Project/ATMSeer#36]
## Description

debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - ATMSeer Version:
  - Vagrant Version:
  - VirtualBox Version:
  - OS Version:

**Comment by micahjsmith** [comment]
Hi @3303387067 can you please edit your issue to include the additional fields we need to understand what is going on (description, expected behavior, actual behavior, steps to reproduce, specifications)?
